name: jhub1onlineapi
version: 0.1.5
author: Marek Kaszewski
description: API to the JHUB1 Online system
dependencies:
  browser: any
  restful:
    git: https://github.com/MarkoVcode/restful.dart
dev_dependencies:
  js: any
  logging_handlers: '>=0.5.0'
  unittest: any
